import { describe, it, expect } from 'vitest';

import { none } from '../../src/maybe.js';
import { Generators, Generator } from '../../src/index.js';

describe('string generators', () => {

  describe('concat', () => {

    it('should produce a string by concatenating the values generated by the given Generator', () => {
      const value = 'abcde';
      const charGenerators = value.split('').map(char => Generators.pure(char));
      expect(Generators.concat(...charGenerators).generate().value).toEqual(value);
    });

    it('should produce the same generator if only one generator is given', () => {
      const generator = Generators.pure('a');
      expect(Generators.concat(generator).generate()).toEqual(generator.generate());
    });

    it('should produce empty string when no generators given', () => {
      expect(Generators.concat().generate().value).toEqual('');
    });
  });

  describe('repeat', () => {

    it('should produce a string by concatenating the values generated by the given Generator', () => {
      const value = 'a';
      const generator = Generators.pure(value);
      const times = 10;

      const expectedValue = [...Array(times)].map(_ => value).join('');

      expect(Generators.repeat(times, generator).generate().value).toEqual(expectedValue);
    });

    it('should produce empty string if repeat is negative or 0', () => {
      const value = 'a';
      const generator = Generators.pure(value);
      expect(Generators.repeat(0, generator).generate().value).toEqual('');
      expect(Generators.repeat(-1, generator).generate().value).toEqual('');
    });

    it('should produce None if provided Generator generates None at least once', () => {
      const generator = Generators.sequenceOf(Generators.pure('a'), Generators.pure('b'), Generators.never());

      expect(Generators.repeat(3, generator).generate()).toEqual(none);
    });
  });

  describe('alphaNumString', () => {
    describeStringGenerator('alphaNumString - fixed length', Generators.alphaNumString(3), /[a-zA-Z0-9]{3}/);
    describeStringGenerator('alphaNumString - one symbol', Generators.alphaNumString(1), /[a-zA-Z0-9]/);
    describeStringGenerator('alphaNumString - empty string', Generators.alphaNumString(0), /.{0}/);
  });

  describe('hexString', () => {
    describeStringGenerator('hexString - fixed length', Generators.hexString(3), /[0-9A-F]{3}/);
    describeStringGenerator('hexString - one symbol', Generators.hexString(1), /[0-9A-F]/);
    describeStringGenerator('hexString - empty string', Generators.hexString(0), /.{0}/);
  });

  describeStringGenerator('asciiRange', Generators.asciiRange(40, 41), /[\(\)]/);
  describeStringGenerator('alphaLowerChar', Generators.alphaLowerChar(), /[a-z]/);
  describeStringGenerator('alphaUpperChar', Generators.alphaUpperChar(), /[A-Z]/);
  describeStringGenerator('alphaChar', Generators.alphaChar(), /[a-zA-Z]/);
  describeStringGenerator('numChar', Generators.numChar(), /[0-9]/);
  describeStringGenerator('alphaNumChar', Generators.alphaNumChar(), /[0-9a-zA-Z]/);
  describeStringGenerator('hexChar', Generators.hexChar(), /[0-9A-F]/);
  describeStringGenerator('asciiChar', Generators.asciiChar(), /[\x20-\x7e]/);
  describeStringGenerator('uuid', Generators.uuid(), /[0-9A-F]{8}\-[0-9A-F]{4}\-4[0-9A-F]{3}\-[89AB][0-9A-F]{3}\-[0-9A-F]{12}/); // RFC 4122 compliant UUID

  describeStringGenerator('identifier', Generators.identifier(5), /[a-z][0-9a-zA-Z]{0,4}/, () => {

    it('should generate none if maxLength is zero', () => {
      expect(Generators.identifier(0).generate()).toEqual(none);
    });

    it('should generate a single character if maxLength is one', () => {
      expect(String(Generators.identifier(1).generate())).toMatch(/[a-z]/);
    });
  });

  describe('stringOf', () => {
    it('produces strings whose characters are drawn from the given char generator', () => {
      const samples = Generators.stringOf(Generators.alphaLowerChar(), { minLength: 0, maxLength: 20 })
        .sampleN(1000, { seed: 'stringOf-domain' });
      expect(samples.every(s => /^[a-z]*$/.test(s))).toBe(true);
    });

    it('honours min/max length bounds', () => {
      const samples = Generators.stringOf(Generators.alphaLowerChar(), { minLength: 3, maxLength: 7 })
        .sampleN(1000, { seed: 'stringOf-bounds' });
      expect(samples.every(s => s.length >= 3 && s.length <= 7)).toBe(true);
    });

    it('covers the full length range across enough samples', () => {
      const samples = Generators.stringOf(Generators.alphaLowerChar(), { minLength: 0, maxLength: 4 })
        .sampleN(1000, { seed: 'stringOf-coverage' });
      const observedLengths = new Set(samples.map(s => s.length));
      expect(observedLengths.has(0)).toBe(true);
      expect(observedLengths.has(4)).toBe(true);
    });

    it('is deterministic for identical seeds', () => {
      const a = Generators.stringOf(Generators.alphaLowerChar(), { minLength: 0, maxLength: 12 })
        .sampleN(50, { seed: 'so-det' });
      const b = Generators.stringOf(Generators.alphaLowerChar(), { minLength: 0, maxLength: 12 })
        .sampleN(50, { seed: 'so-det' });
      expect(a).toEqual(b);
    });

    it('yields none when maxLength < minLength', () => {
      expect(Generators.stringOf(Generators.alphaLowerChar(), { minLength: 5, maxLength: 2 }).generate())
        .toEqual(none);
    });

    it('carries a default shrinker', () => {
      expect(Generators.stringOf(Generators.alphaLowerChar(), { maxLength: 5 }).shrinker).toBeDefined();
    });
  });

  describe('nonEmptyString', () => {
    it('never produces empty strings', () => {
      const samples = Generators.nonEmptyString({ maxLength: 10 })
        .sampleN(1000, { seed: 'nes-nonempty' });
      expect(samples.every(s => s.length >= 1)).toBe(true);
    });

    it('honours the maxLength bound', () => {
      const samples = Generators.nonEmptyString({ maxLength: 6 })
        .sampleN(1000, { seed: 'nes-bound' });
      expect(samples.every(s => s.length >= 1 && s.length <= 6)).toBe(true);
    });

    it('uses printable ASCII by default', () => {
      const samples = Generators.nonEmptyString({ maxLength: 10 })
        .sampleN(1000, { seed: 'nes-domain' });
      expect(samples.every(s => /^[\x20-\x7e]+$/.test(s))).toBe(true);
    });

    it('respects a custom charGen', () => {
      const samples = Generators.nonEmptyString({ maxLength: 8, charGen: Generators.numChar() })
        .sampleN(1000, { seed: 'nes-custom' });
      expect(samples.every(s => /^[0-9]+$/.test(s))).toBe(true);
    });
  });

  describe('asciiString', () => {
    it('produces only printable ASCII characters', () => {
      const samples = Generators.asciiString({ maxLength: 30 })
        .sampleN(1000, { seed: 'ascii-domain' });
      expect(samples.every(s => /^[\x20-\x7e]*$/.test(s))).toBe(true);
    });

    it('is deterministic for identical seeds', () => {
      const a = Generators.asciiString({ maxLength: 20 }).sampleN(100, { seed: 'as-det' });
      const b = Generators.asciiString({ maxLength: 20 }).sampleN(100, { seed: 'as-det' });
      expect(a).toEqual(b);
    });
  });

  describe('unicodeString', () => {
    it('contains only BMP code points', () => {
      const samples = Generators.unicodeString({ maxLength: 30 })
        .sampleN(1000, { seed: 'uni-bmp' });
      for (const s of samples) {
        for (let i = 0; i < s.length; i++) {
          const code = s.charCodeAt(i);
          expect(code).toBeGreaterThanOrEqual(0);
          expect(code).toBeLessThanOrEqual(0xffff);
        }
      }
    });

    it('rejects lone surrogates', () => {
      const samples = Generators.unicodeString({ maxLength: 50 })
        .sampleN(1000, { seed: 'uni-surrogate' });
      for (const s of samples) {
        for (let i = 0; i < s.length; i++) {
          const code = s.charCodeAt(i);
          expect(code < 0xd800 || code > 0xdfff).toBe(true);
        }
      }
    });

    it('is deterministic for identical seeds', () => {
      const a = Generators.unicodeString({ maxLength: 20 }).sampleN(100, { seed: 'uni-det' });
      const b = Generators.unicodeString({ maxLength: 20 }).sampleN(100, { seed: 'uni-det' });
      expect(a).toEqual(b);
    });
  });

  describe('numericString', () => {
    it('produces only digits', () => {
      const samples = Generators.numericString({ maxLength: 20 })
        .sampleN(1000, { seed: 'num-domain' });
      expect(samples.every(s => /^[0-9]*$/.test(s))).toBe(true);
    });

    it('is deterministic for identical seeds', () => {
      const a = Generators.numericString({ maxLength: 12 }).sampleN(100, { seed: 'num-det' });
      const b = Generators.numericString({ maxLength: 12 }).sampleN(100, { seed: 'num-det' });
      expect(a).toEqual(b);
    });
  });

  describe('shrinkString', () => {
    it('yields nothing for the empty string', () => {
      expect([...Generators.shrinkString('')]).toEqual([]);
    });

    it('yields the empty string first for non-empty inputs', () => {
      const out = [...Generators.shrinkString('hello')];
      expect(out[0]).toBe('');
    });

    it('produces strictly shorter candidates', () => {
      const out = [...Generators.shrinkString('abcd')];
      expect(out.some(s => s.length < 4)).toBe(true);
    });
  });

  function describeStringGenerator(generatorName: string, generator: Generator<string>, expectedRegex: RegExp, moreSpecs: () => void = () => {}) {
    describe(generatorName, () => {
      const triesNumber = 10;

      const generatedStrings = [...Array(triesNumber)].map(_ =>
        generator.generate()
      );

      it(`should generate strings matching ${expectedRegex}`, () => {
        expect(generatedStrings.every(char => char.isDefined)).toBe(true);
        expect(generatedStrings.every(char => expectedRegex.test(char.get()))).toBe(true);
      });

      it('should generate different strings', () => {
        const uniqueGeneratedStrings = new Set(generatedStrings);
        expect(uniqueGeneratedStrings.size).toBeGreaterThan(1);
      });

      moreSpecs();
    });
  }
});
